# Trying out loading env configurations using YAML files

APP:
  ENVIRONMENT: dev
  DEBUG: True
  # Only accept True or False

DATABASE:
  USERNAME: postgres
  PASSWORD: admin123
  HOST: localhost
  DB: formula_1_db